### ISSUE TITLE
Exporter exiting when no data is returned  from a metric definition available 

### ISSUE THREAD

**Issue by mariobede** [RobustPerception/azure_metrics_exporter#35]
Exporter exiting when no data exists for  one metric.

```2018/11/12 13:11:00 GET https://management.azure.com/subscriptions/XXXXXXXXXXX/resourceGroups/XXXXXXXsbn-rg/providers/Microsoft.ServiceBus/namespaces/XXXXXXXX/providers/microsoft.insights/metrics?aggregation=Total%2CAverage%2CMinimum%2CMaximum&api-version=2018-01-01&metricnames=SuccessfulRequests%2CServerErrors%2CUserErrors%2CIncomingRequests%2CIncomingMessages%2COutgoingMessages%2CActiveConnections%2CSize%2CMessages%2CActiveMessages%2CDeadletteredMessages%2CScheduledMessages%2CThrottledRequests&timespan=2018-11-12T13%3A07%3A00Z%2F2018-11-12T13%3A08%3A00Z
panic: runtime error: index out of range

goroutine 16 [running]:
panic(0x3d3640, 0xc42000a0f0)
	/usr/local/Cellar/go/1.7.5/libexec/src/runtime/panic.go:500 +0x1a1
main.(*Collector).Collect(0x678d90, 0xc420327500)
	/usr/local/Cellar/go/1.7.5/bin/src/github.com/RobustPerception/azure_metrics_exporter/main.go:71 +0xd97
github.com/RobustPerception/azure_metrics_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc420396ad0, 0xc420327500, 0x63b720, 0x678d90)
	/usr/local/Cellar/go/1.7.5/bin/src/github.com/RobustPerception/azure_metrics_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:383 +0x63
created by github.com/RobustPerception/azure_metrics_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/usr/local/Cellar/go/1.7.5/bin/src/github.com/RobustPerception/azure_metrics_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:384 +0x326
```

Config:

``` targets:
  - resource: "/resourceGroups/xXXXX-rg/providers/Microsoft.ServiceBus/namespaces/XXXX"
    metrics:
      - name: "SuccessfulRequests"
      - name: "ServerErrors"
      - name: "UserErrors"
      - name: "IncomingRequests"
      - name: "IncomingMessages"
      - name: "OutgoingMessages"
      - name: "ActiveConnections"
      - name: "Size"
      - name: "Messages"
      - name: "ActiveMessages"
      - name: "DeadletteredMessages"
      - name: "ScheduledMessages"
      - name: "ThrottledRequests"
```

ThrottledRequests -> This is the guilty guy. If configured only on its own or removed from the list. there is no failure.

```╰─ ./azure_metrics_exporter --list.definitions
2018/11/12 12:55:14 Resource: XXXXX

Available Metrics:
2018/11/12 12:55:14 - SuccessfulRequests
2018/11/12 12:55:14 - ServerErrors
2018/11/12 12:55:14 - UserErrors
2018/11/12 12:55:14 - ThrottledRequests
2018/11/12 12:55:14 - IncomingRequests
2018/11/12 12:55:14 - IncomingMessages
2018/11/12 12:55:14 - OutgoingMessages
2018/11/12 12:55:14 - ActiveConnections
2018/11/12 12:55:14 - Size
2018/11/12 12:55:14 - Messages
2018/11/12 12:55:14 - ActiveMessages
2018/11/12 12:55:14 - DeadletteredMessages
2018/11/12 12:55:14 - ScheduledMessages```

**Comment by marioanton** [comment]
i'm tempted to give it a "go" but my lack of knowledge might difficult t.

**Comment by brian-brazil** [comment]
`len(value.Timeseries) > 0` is the main bit you need.

**Comment by marioanton** [comment]
👍  will take a peak.
